spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: ''
    url: jdbc:h2:file:./data/basecamp

logging:
  level:
    root: WARN
    com.soavedev.seeddesafiobasecamp: DEBUG
    com.soavedev.seeddesafiobasecamp.service: TRACE
    org.springframework.web.client.RestTemplate: ERROR
    org.springframework.security: INFO