spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: 'admin'
    password: 'admin'
    url: jdbc:mysql://127.0.0.1/basecamp
logging:
  level:
    root: WARN
    com.soavedev.seeddesafiobasecamp: DEBUG
    com.soavedev.seeddesafiobasecamp.service: TRACE
    org.springframework.web.client.RestTemplate: ERROR
    org.springframework.security: INFO