spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: mysql
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    url: jdbc:h2:file:./data/basecamp