spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    url: jdbc:h2:file:./data/basecamp
logging:
  level:
    root: WARN
    com.soavedev.seeddesafiobasecamp: DEBUG
    org.springframework.web.client.RestTemplate: ERROR